server:
  port: 8080

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9000

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/wxsystem?serverTimezone=GMT%2B8"
    username: "root"
    password: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: localhost
    timeout: 6000ms
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
wx:
  jwt:
    secret: gts0gm088mc096ad99173hrrsfsg8xb9[www.lixingyong.com]
    expire: 604800
    header: token
  xcx:
    appid: wxdcb9fb2e8b409568
    appsecret: aa428c00f5e758bde71bf64b5f67c3be

neusoft:
  username: lixingyong15&congyouzhi15
  password: 209715&350615

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.lixingyong.meneusoft.modules.*.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true