server:
  port: 8080
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9000


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/me_neusoft?serverTimezone=GMT%2B8"
    username: "root"
    password: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: localhost
    timeout: 6000ms
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
wx:
  jwt:
    # 你的secret密匙
    secret: gts0gm188mc096ad923453hrrsfsg8xb9[www.lixingyong.com]
    expire: 604800
    header: Authorization
  xcx:
    # 小程序ID和密匙
    appid: 
    appsecret: 

neusoft:
  # 校园网账号密码
  username: 
  password: 

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.lixingyong.meneusoft.modules.*.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    meta-object-handler: com.lixingyong.meneusoft.common.handler.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
#logging:
#  path: meneusoft.log
#  level:
#    root: WARN
#    com:
#      lixingyong:
#        neusoft: WARN